FROM containername-image
WORKDIR /code
COPY ./code/* ./
RUN apt install -y build-essential
RUN apt install -y libmariadbclient-dev
RUN pip install -U pip \
    && pip install -r requirements.txt
EXPOSE 8080
CMD [ "gunicorn","--bind","0.0.0.0:8080", "main.wsgi"]